PACKAGE = "org.w3c.jigsaw.http"

JIGSAWPACKAGES = \
	socket \
	mux

JIGSAWFILES = \
	Client.java \
	ClientException.java \
	ClientFactory.java \
	CommonLogger.java \
	ExtendedCommonLogger.java \
	ConfigResource.java \
	HTTPException.java \
	HTTPRuntimeException.java \
	HTTPFilter.java \
	Logger.java \
	MimeClientFactory.java \
	Reply.java \
	Request.java \
	Shuffler.java \
	httpd.java \
	httpdPreloadInterface.java \
	httpdSecurityManager.java \
	httpdStatistics.java \
	ConnectionProp.java \
	GeneralProp.java \
	LoggingProp.java \
	UnixProp.java \
	ControlResource.java

PACKAGES = $(JIGSAWPACKAGES)
FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
include $(TOP)/makefiles/package.make
