PACKAGE=org.w3c.www.mux

JIGSAWFILES = \
	MUX.java \
	MuxInputStream.java \
	MuxOutputStream.java \
	MuxReader.java \
	MuxSession.java \
	MuxStream.java \
	MuxWriter.java \
	MuxStreamHandler.java \
	MuxProtocolHandler.java \
	SampleMuxHandler.java

JIGSAWPACKAGES = \
	handlers \
	tests

PACKAGES = $(JIGSAWPACKAGES)
FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
include $(TOP)/makefiles/package.make
