PACKAGE="org.w3c.jigedit.cvs"

JIGSAWFILES = \
	CvsDirectoryHandler.java \
	CvsEntryResource.java \
	CvsFrame.java \
	CvsHandlerInterface.java \
	CvsModule.java \
	CvsProp.java \
	CvsRootDirectory.java \
	CvsRootPassDirectory.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
