PACKAGE = "org.w3c.tools.resources.store"

JIGSAWFILES = \
	InvalidStoreClassException.java \
	UnknownResourceException.java \
	NewStoreEntry.java \
	NotAStoreException.java \
	ResourceStore.java \
	ResourceStoreImpl.java \
	ResourceStoreManager.java \
	ResourceStoreState.java \
	StoreClassVersionException.java

FILES = $(JIGSAWFILES)

TOP=../../../../../..
include $(TOP)/makefiles/file.make
