PACKAGE="org.w3c.jigadm"


JIGSAWFILES = \
	Main.java \
	RemoteResourceWrapper.java \
	PropertyManager.java

JIGSAWPACKAGES = \
	events \
        editors \
	gui

PACKAGES = $(JIGSAWPACKAGES)
FILES = $(JIGSAWFILES)

TOP=../../../..
include $(TOP)/makefiles/file.make
include $(TOP)/makefiles/package.make

