PACKAGE = "org.w3c.www.mime"

JIGSAWFILES = \
	MimeHeaderHolder.java \
	MimeParser.java \
	MimeParserException.java \
	MimeParserFactory.java \
	MimeType.java \
	MimeTypeFormatException.java \
	MultipartInputStream.java \
	MimeHeaders.java \
	MimeHeadersFactory.java \
	LanguageTag.java \
	Utils.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
