PACKAGE="org.w3c.jigsaw.https.socket"

JIGSAWFILES = \
	SSLSocketClientFactory.java \
	SSLSocketClient.java \
	SSLProperties.java

FILES = $(JIGSAWFILES)

TOP=../../../../../..
include $(TOP)/makefiles/file.make
