PACKAGE="org.w3c.jigsaw"

JIGSAWFILES = \
	Main.java

JIGSAWPACKAGES = \
	acl \
	auth \
	admin \
	ccpp \
	config \
	daemon \
	filters \
	frames \
	forms \
	html \
	http \
	https \
	indexer \
	pagecompile \
	pics \
	proxy \
	resources \
	servlet \
	ssi \
	status \
	tests \
	tutorials \
	webdav \
	webdavs \
	zip

# removed: map

PACKAGES = $(JIGSAWPACKAGES)
FILES = $(JIGSAWFILES)

TOP=../../../..
include $(TOP)/makefiles/package.make
include $(TOP)/makefiles/file.make
