PACKAGE = "org.w3c.jigsaw.proxy"

JIGSAWFILES = \
	CacheProp.java \
	ForwardFrame.java \
	ProxyDispatcherProp.java \
	ProxyFrame.java \
	ProxyExtFrame.java \
	ProxyRequestObserver.java \
	MirrorFrame.java \
	ProxyProp.java 

# removed temporarily	CacheProp.java 

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make


