PACKAGE = "org.w3c.www.webdav"

JIGSAWFILES = \
	DAVIf.java \
	DAVIfList.java \
	DAVParser.java \
	DAVEntityTag.java \
	DAVStateToken.java \
	DAVStatusURI.java \
	DAVStatusURIList.java \
	DAVTimeout.java \
	InvalidDAVBodyException.java \
	ParseState.java \
	WEBDAV.java

JIGSAWPACKAGES = \
	xml

FILES = $(JIGSAWFILES)

PACKAGES = $(JIGSAWPACKAGES)


TOP=../../../../..
include $(TOP)/makefiles/file.make
include $(TOP)/makefiles/package.make
