/* Generated By:JavaCC: Do not edit this line. ijConstants.java */
package org.apache.derby.impl.tools.ij;

public interface ijConstants {

  int EOF = 0;
  int SINGLE_LINE_SQLCOMMENT = 7;
  int ABSOLUTE = 8;
  int AFTER = 9;
  int ALIASES = 10;
  int ALL = 11;
  int AS = 12;
  int ASYNC = 13;
  int ATTRIBUTES = 14;
  int AUTOCOMMIT = 15;
  int BANG = 16;
  int BEFORE = 17;
  int CLOSE = 18;
  int COMMIT = 19;
  int CONNECT = 20;
  int CONNECTION = 21;
  int CONNECTIONS = 22;
  int CURRENT = 23;
  int CURSOR = 24;
  int DESCRIBE = 25;
  int DISCONNECT = 26;
  int DRIVER = 27;
  int ELAPSEDTIME = 28;
  int END = 29;
  int EQUALS_OPERATOR = 30;
  int EXECUTE = 31;
  int EXIT = 32;
  int EXPECT = 33;
  int FAIL = 34;
  int FIRST = 35;
  int FOR = 36;
  int FROM = 37;
  int GET = 38;
  int GETCURRENTROWNUMBER = 39;
  int HOLD = 40;
  int HELP = 41;
  int IN = 42;
  int INDEXES = 43;
  int INSENSITIVE = 44;
  int INTO = 45;
  int LAST = 46;
  int LOCALIZEDDISPLAY = 47;
  int MAXIMUMDISPLAYWIDTH = 48;
  int NAME = 49;
  int NEXT = 50;
  int NOHOLD = 51;
  int NOHOLDFORCONNECTION = 52;
  int OFF = 53;
  int ON = 54;
  int PASSWORD = 55;
  int PERIOD = 56;
  int PREPARE = 57;
  int PREVIOUS = 58;
  int PROCEDURE = 59;
  int PROCEDURES = 60;
  int PROPERTIES = 61;
  int PROTOCOL = 62;
  int QUIT = 63;
  int READONLY = 64;
  int RELATIVE = 65;
  int REMOVE = 66;
  int RESOURCE = 67;
  int ROLLBACK = 68;
  int RUN = 69;
  int TO = 70;
  int SAVEPOINT = 71;
  int SCHEMAS = 72;
  int SCROLL = 73;
  int SENSITIVE = 74;
  int SET = 75;
  int SHOW = 76;
  int SHUTDOWN = 77;
  int STATEMENT = 78;
  int SYNONYMS = 79;
  int TABLES = 80;
  int USER = 81;
  int USING = 82;
  int VIEWS = 83;
  int WAIT = 84;
  int WITH = 85;
  int XA_1PHASE = 86;
  int XA_2PHASE = 87;
  int XA_DATASOURCE = 88;
  int XA_CONNECT = 89;
  int XA_COMMIT = 90;
  int XA_DISCONNECT = 91;
  int XA_END = 92;
  int XA_ENDRSCAN = 93;
  int XA_FAIL = 94;
  int XA_FORGET = 95;
  int XA_GETCONNECTION = 96;
  int XA_JOIN = 97;
  int XA_NOFLAGS = 98;
  int XA_PREPARE = 99;
  int XA_RECOVER = 100;
  int XA_RESUME = 101;
  int XA_ROLLBACK = 102;
  int XA_START = 103;
  int XA_STARTRSCAN = 104;
  int XA_SUCCESS = 105;
  int XA_SUSPEND = 106;
  int DATASOURCE = 107;
  int CP_DATASOURCE = 108;
  int CP_CONNECT = 109;
  int CP_GETCONNECTION = 110;
  int CP_DISCONNECT = 111;
  int WORK = 112;
  int COMMA = 113;
  int LEFT_PAREN = 114;
  int RIGHT_PAREN = 115;
  int DOUBLE_QUOTE = 116;
  int HASH = 117;
  int MINUS_SIGN = 118;
  int PLUS_SIGN = 119;
  int IDENTIFIER = 120;
  int LETTER = 121;
  int DIGIT = 122;
  int INTEGER = 123;
  int STRING = 124;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_SQLCOMMENT>",
    "\"absolute\"",
    "\"after\"",
    "\"aliases\"",
    "\"all\"",
    "\"as\"",
    "\"async\"",
    "\"attributes\"",
    "\"autocommit\"",
    "\"!\"",
    "\"before\"",
    "\"close\"",
    "\"commit\"",
    "\"connect\"",
    "\"connection\"",
    "\"connections\"",
    "\"current\"",
    "\"cursor\"",
    "\"describe\"",
    "\"disconnect\"",
    "\"driver\"",
    "\"elapsedtime\"",
    "\"end\"",
    "\"=\"",
    "\"execute\"",
    "\"exit\"",
    "\"expect\"",
    "\"fail\"",
    "\"first\"",
    "\"for\"",
    "\"from\"",
    "\"get\"",
    "\"getcurrentrownumber\"",
    "\"hold\"",
    "\"help\"",
    "\"in\"",
    "\"indexes\"",
    "\"insensitive\"",
    "\"into\"",
    "\"last\"",
    "\"localizeddisplay\"",
    "\"maximumdisplaywidth\"",
    "\"name\"",
    "\"next\"",
    "\"nohold\"",
    "\"noholdforconnection\"",
    "\"off\"",
    "\"on\"",
    "\"password\"",
    "\".\"",
    "\"prepare\"",
    "\"previous\"",
    "\"procedure\"",
    "\"procedures\"",
    "\"properties\"",
    "\"protocol\"",
    "\"quit\"",
    "\"readonly\"",
    "\"relative\"",
    "\"remove\"",
    "\"resource\"",
    "\"rollback\"",
    "\"run\"",
    "\"to\"",
    "\"savepoint\"",
    "\"schemas\"",
    "\"scroll\"",
    "\"sensitive\"",
    "\"set\"",
    "\"show\"",
    "\"shutdown\"",
    "\"statement\"",
    "\"synonyms\"",
    "\"tables\"",
    "\"user\"",
    "\"using\"",
    "\"views\"",
    "\"wait\"",
    "\"with\"",
    "\"XA_1phase\"",
    "\"XA_2phase\"",
    "\"XA_datasource\"",
    "\"XA_connect\"",
    "\"XA_commit\"",
    "\"XA_disconnect\"",
    "\"XA_end\"",
    "\"XA_endrscan\"",
    "\"XA_fail\"",
    "\"XA_forget\"",
    "\"XA_getconnection\"",
    "\"XA_join\"",
    "\"XA_noflags\"",
    "\"XA_prepare\"",
    "\"XA_recover\"",
    "\"XA_resume\"",
    "\"XA_rollback\"",
    "\"XA_start\"",
    "\"XA_startrscan\"",
    "\"XA_success\"",
    "\"XA_suspend\"",
    "\"datasource\"",
    "\"CP_datasource\"",
    "\"CP_connect\"",
    "\"CP_getconnection\"",
    "\"CP_disconnect\"",
    "\"work\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"#\"",
    "\"-\"",
    "\"+\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER>",
    "<STRING>",
  };

}
