/* Generated By:JavaCC: Do not edit this line. mtGrammarConstants.java */
package org.apache.derby.impl.tools.ij;

public interface mtGrammarConstants {

  int EOF = 0;
  int SINGLE_LINE_SQLCOMMENT = 7;
  int SINGLE_LINE_COMMENT = 8;
  int SINGLE_LINE_COMMENT2 = 9;
  int CASE = 10;
  int FILE = 11;
  int LAST = 12;
  int INIT = 13;
  int WEIGHT = 14;
  int DESCRIPTION = 15;
  int IGNOREERRORS = 16;
  int PROPERTIES = 17;
  int THREADS = 18;
  int RUNTIME = 19;
  int INT = 20;
  int WORD = 21;
  int STRING = 22;
  int COMMA = 23;
  int COLON = 24;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_SQLCOMMENT>",
    "<SINGLE_LINE_COMMENT>",
    "<SINGLE_LINE_COMMENT2>",
    "\"case:\"",
    "\"file:\"",
    "\"last:\"",
    "\"init:\"",
    "\"weight:\"",
    "\"description:\"",
    "\"ignoreErrors:\"",
    "\"properties:\"",
    "\"threads:\"",
    "\"runtime:\"",
    "<INT>",
    "<WORD>",
    "<STRING>",
    "\",\"",
    "\":\"",
  };

}
