PACKAGE = "org.w3c.jigsaw.auth"

JIGSAWFILES = \
	AuthFilter.java \
	AuthRealm.java \
	AuthUser.java \
	GenericAuthFilter.java \
	DigestAuthFilter.java \
	IPMatcher.java \
	IPTemplatesAttribute.java \
	PasswordAttribute.java \
	RealmsCatalog.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make


