PACKAGE = "org.w3c.jigsaw.pics"

JIGSAWFILES = \
	SampleLabel.java \
	SampleLabelBureau.java \
	LabelBureauResource.java \
	LabelBureauFrame.java \
	LabelBureauFactory.java \
	SampleLabelService.java \
	PICS.java \
	PICSFilter.java  \
	UnknownServiceException.java \
	LabelInterface.java \
	LabelServiceInterface.java \
	LabelBureauInterface.java \
	InvalidLabelException.java \
	InvalidLabelFileException.java \
	InvalidRequestException.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
