PACKAGE = "org.w3c.tools.resources.indexer"

JIGSAWFILES = \
	IndexersCatalog.java \
	ResourceIndexer.java \
	TemplateContainer.java \
	SampleResourceIndexer.java \
	GhostResourceIndexer.java \
	IndexerModule.java

FILES = $(JIGSAWFILES)

TOP=../../../../../..
include $(TOP)/makefiles/file.make
