PACKAGE  = "org.w3c.www.protocol.http.proxy"

JIGSAWFILES = \
	ProxyDispatcher.java \
	Rule.java \
	RuleNode.java \
	RuleParser.java \
	RuleParserException.java

FILES = $(JIGSAWFILES)

TOP=../../../../../../..
include $(TOP)/makefiles/file.make
