PACKAGE = "org.w3c.jigsaw.ssi.commands"

JIGSAWFILES = \
	BasicCommand.java \
	BasicCommandRegistry.java \
	Command.java \
	CommandRegistry.java \
	ConfigCommand.java \
	ControlCommand.java \
	ControlCommandException.java \
	CookieCommand.java \
	CountCommand.java \
	CounterCommand.java \
	DefaultCommandRegistry.java \
	EchoCommand.java \
	ElseCommand.java \
	EndifCommand.java \
	EndloopCommand.java \
	ExecCommand.java \
	ExitloopCommand.java \
	FLastModCommand.java \
	FSizeCommand.java \
	IfCommand.java \
	IncludeCommand.java \
	LoopCommand.java \
	SampleCommand.java

FILES = $(JIGSAWFILES)

TOP=../../../../../..
include $(TOP)/makefiles/file.make
