PACKAGE = "org.w3c.tools.sexpr"

JIGSAWFILES = \
	Cons.java \
	DoubleFix.java \
	Readtable.java \
	SExpr.java \
	SExprParser.java \
	SExprParserException.java \
	SExprStream.java \
	SimpleReadtable.java \
	SimpleSExprStream.java \
	Symbol.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make

