PACKAGE = "org.w3c.jigsaw.pagecompile"

JIGSAWFILES = \
	GeneratedFrame.java \
	GeneratedClassLoader.java \
        JDKCompiler.java \
	PageCompileFile.java \
	PageCompileFrame.java \
	PageCompileProp.java \
	PageCompileOutputStream.java \
        PageCompiler.java \
	Segment.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
