PACKAGE=org.w3c.tools.forms

JIGSAWFILES = \
	BooleanField.java \
	DateField.java \
	DoubleField.java \
	FileField.java \
	Form.java \
	FormField.java \
	FormHandlerInterface.java \
	FormManager.java \
	FormPanel.java \
	IllegalFieldValueException.java \
	IntegerField.java \
	OptionField.java \
	RangedIntegerField.java \
	StringField.java 

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
