PACKAGE="org.w3c.jigsaw.https"

JIGSAWFILES = \
	SSLAdapter.java \
	httpsd.java

JIGSAWPACKAGES = \
	socket

# removed: map

PACKAGES = $(JIGSAWPACKAGES)
FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/package.make
include $(TOP)/makefiles/file.make
