PACKAGE = "org.w3c.www.protocol.http.cache"

JIGSAWPACKAGES = \
	push

JIGSAWFILES = \
	ActiveStream.java \
	CacheFilter.java \
	CacheGeneration.java \
	CachedResource.java \
	CachedResourceFactory.java \
	CacheSerializer.java \
	CacheState.java \
	CacheStore.java \
	CacheSweeper.java \
	CacheValidator.java \
	InvalidCacheException.java \
	EntityCachedResource.java \
	NoSuchResourceException.java \
	SimpleCacheSerializer.java \
	SimpleCacheSweeper.java \
	SimpleCacheValidator.java \
	StoreState.java \
	TeeMonitor.java \
	UnloadedGenerationException.java

PACKAGES = $(JIGSAWPACKAGES)
FILES = $(JIGSAWFILES)

TOP=../../../../../../..
include $(TOP)/makefiles/file.make
include $(TOP)/makefiles/package.make

