# Package name

PACKAGE="org.w3c.tools.offline.command"

JIGSAWFILES = \
		CommandInterpreter.java \
		CommandLine.java \
		CommandParseException.java \
		Main.java

FILES = $(JIGSAWFILES)

TOP=../../../../../..
include $(TOP)/makefiles/file.make
