PACKAGE = "org.w3c.jigsaw.filters"

JIGSAWFILES = \
	AccessLimitFilter.java \
	CacheFilter.java \
	CookieFilter.java \
	CounterFilter.java \
	DebugFilter.java \
	ErrorFilter.java \
	GZIPFilter.java \
	HeaderFilter.java \
	HourLimiterFilter.java \
	LogFilter.java \
	NoCacheFilter.java \
	ProcessFilter.java \
	PutSizeFilter.java \
	RegexRedirectFilter.java \
	RequestedHeaderFilter.java \
	SimpleCacheFilter.java \
	TEFilter.java \
	URISizeLimiterFilter.java \
	UseProxyFilter.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
