PACKAGE="org.w3c.tools.resources.upgrade"

JIGSAWFILES = \
	Attribute.java \
	AttributeRegistry.java \
	BooleanAttribute.java \
	ClassAttribute.java \
	DateAttribute.java \
	DoubleAttribute.java \
	EncodingAttribute.java \
	FileAttribute.java \
	FilenameAttribute.java \
	FrameArrayAttribute.java \
	IPTemplatesAttribute.java \
	IntegerArrayAttribute.java \
	IntegerAttribute.java \
	LanguageAttribute.java \
	LongAttribute.java \
	MimeTypeArrayAttribute.java \
	MimeTypeAttribute.java \
	ObjectAttribute.java \
	PasswordAttribute.java \
	PropertiesAttribute.java \
	SegmentArrayAttribute.java \
	StringArrayAttribute.java \
	StringAttribute.java \
	UpgradeException.java \
	Upgrader.java

FILES = $(JIGSAWFILES)

TOP=../../../../../..
include $(TOP)/makefiles/file.make
