PACKAGE=org.w3c.tools.jdbc

JIGSAWFILES = \
	ConnectionManager.java \
	Jdbc.java \
	JdbcBeanAdapter.java \
	JdbcBeanAdapterBeanInfo.java \
	JdbcBeanInterface.java \
	JdbcBeanInterfaceBeanInfo.java \
	JdbcBeanSerializer.java \
	JdbcBeanUtil.java \
	JdbcConnection.java \
	JdbcPropertyChangeSupport.java \
	JdbcServer.java \
	JdbcServerState.java \
	PropertyCache.java \
	SQL.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
