PACKAGE  = "org.w3c.www.protocol.http"

JIGSAWPACKAGES = \
	auth \
	cache \
	cookies \
	icp \
	micp \
	proxy

#removed for now cache icp micp

JIGSAWFILES = \
	HttpManager.java \
	RequestFilter.java \
	RequestObserver.java \
	RequestProcessor.java \
	Reply.java \
	Request.java \
	HttpServer.java \
	HttpBasicServer.java \
	HttpURLConnection.java \
	HttpConnection.java \
	Handler.java \
	FilterEngine.java \
	DebugFilter.java \
	PropRequestFilter.java \
	RequestEvent.java \
	ContinueEvent.java \
	ConnectedEvent.java \
	HttpBasicConnection.java \
	HttpMuxConnection.java \
	HttpMuxServer.java \
	HttpException.java \
	PropRequestFilterException.java \
	HttpServerState.java

PACKAGES = $(JIGSAWPACKAGES)
FILES = $(JIGSAWFILES)

TOP=../../../../../..
include $(TOP)/makefiles/file.make
include $(TOP)/makefiles/package.make
