PACKAGE = "org.w3c.jigadm.gui"

JIGSAWFILES = \
	TreeListener.java \
	ResourceEditorListener.java \
	ServerBrowser.java \
	AuthPopup.java 

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make

