PACKAGE=org.w3c.tools.jpeg

JIGSAWFILES = \
	Exif.java \
	ExifData.java \
	JpegException.java \
	Jpeg.java \
	JpegHeaders.java \
	JpegCommentHandler.java \
	JpegCommentWriter.java \
	TagDecoder.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
