PACKAGE = "org.w3c.jigadmin.widgets"

JIGSAWFILES = \
	ClosableFrame.java \
	ClosableDialog.java \
	DnDJPanel.java \
	DnDTabbedPane.java \
	DoubleTextField.java \
	DraggableList.java \
	EditableSlider.java \
	EditableStringChoice.java \
	Icons.java \
	IntegerTextField.java \
	ListEditor.java \
	StringChoice.java

FILES = $(JIGSAWFILES)

TOP=../../../../..
include $(TOP)/makefiles/file.make
